name: Deploy to integrated Sandbox

on:
  push:
    branches:
      - development
    paths:
      - 'force-app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: 'Populate auth file with SFDX_URL secret of integration org'
        shell: bash
        run: |
          echo ${{ secrets.SFDX_AUTH_URL}} > ./SFDX_AUTH_URL.txt

      - name: 'Authenticate to Integration Org'
        run: sfdx force:auth:sfdxurl:store -f ./SFDX_AUTH_URL.txt -s -a integration

      - name: Deploy to Integration org
        run: sfdx force:source:deploy -p force-app -u integration --testlevel RunLocalTests --json

